# hugo.toml

baseURL = 'https://example.org/'
languageCode = 'ja-jp'
title = 'SQL Master Hub'
alt_theme = 'sqldocs' # 作成したテーマを指定
theme = 'sqlearn1'

# Goldmarkレンダラー設定
[markup.goldmark.renderer]
  # マークダウンファイル内でのHTMLタグ記述を許可する
  unsafe = true

[markup.highlight]
  # インラインスタイルを生成せず、CSSクラスを使用するようにする
  noClasses = false
